[package]
name = "super-engine-bros"
version = "0.1.0-dev"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["gamedev", "game-engine", "ecs", "wgpu", "mario"]
categories = ["game-engines", "rendering", "graphics"]

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
pollster = "1.0.1"
wgpu = "30.0.0"
winit = { version = "0.30.13", features = ["rwh_06"] }
